### ISSUE TITLE
Refactor add_statistics function

### ISSUE THREAD

**Issue by atyoshioka** [petabi/review#171]
How `add_statistics` function works is basically as follows:

1. iterate over the data sent by REconverge and push it to several `Structs` like 
    ```
    Vec<ColumnDescriptionTable>
    Vec<DescriptionInt>
    Vec<TopInt>
    Vec<DescriptionFloat>
    Vec<TopNFloat>
    ...
    ```
depending on the column type with dummy value of `description_id`.

2. insert `Vec<ColumnDescriptionTable>` into the database and receive the inserted rows including `description_id`s which are dynamically assigned by the database.
3. iterate over all `Structs` to replace the dummy value of `description_id` with the correct `description_id`
4. insert all the remaining `Structs` into the database

This approach is very inefficient and the code does not look good. Need some serious refactoring.

**Comment by atyoshioka** [comment]
@sehkone I am testing the current `add_statistics` function and have a question about the behavior. Even if I use the same dataset, the result of `top_n_int` varies like below:

```
database name: review12
review12=# select * from column_description where id = 30 or id = 31;
 id | cluster_id | first_event_id | last_event_id | column_index | type_id | count | unique_count 
----+------------+----------------+---------------+--------------+---------+-------+--------------
 30 |         31 | 96             | 293302        |            7 |       1 |     3 |            3
 31 |         31 | 96             | 293302        |            8 |       1 |     3 |            3
(2 rows)

review12=# select * from top_n_int where description_id = 30 or description_id = 31;
 id | description_id | ranking |   value    | count 
----+----------------+---------+------------+-------
  8 |             30 |       1 | 4131274604 |     1
  9 |             30 |       2 | 2328995106 |     1
 10 |             30 |       3 |   97308335 |     1
 11 |             31 |       1 | 4131274604 |     1
 12 |             31 |       2 |   97308335 |     1
 13 |             31 |       3 | 2328995106 |     1


database name: review13
review13=# select * from column_description where id = 30 or id = 31;
 id | cluster_id | first_event_id | last_event_id | column_index | type_id | count | unique_count 
----+------------+----------------+---------------+--------------+---------+-------+--------------
 30 |         31 | 96             | 293302        |            7 |       1 |     3 |            3
 31 |         31 | 96             | 293302        |            8 |       1 |     3 |            3
(2 rows)

review13=# select * from top_n_int where description_id = 30 or description_id = 31;
 id | description_id | ranking |   value    | count 
----+----------------+---------+------------+-------
  8 |             30 |       1 | 2328995106 |     1
  9 |             30 |       2 |   97308335 |     1
 10 |             30 |       3 | 4131274604 |     1
 11 |             31 |       1 |   97308335 |     1
 12 |             31 |       2 | 4131274604 |     1
 13 |             31 |       3 | 2328995106 |     1
```

Why this happens? What is the relationship between `ranking` and `value` in `top_n_int` table?

**Comment by sehkone** [comment]
Yes, `ranking` is based on the value of `count`. `sort_unstable_by` caused changing of the order. I think this is not a big deal with many data.

**Comment by atyoshioka** [comment]
What is the purpose to have `ranking` column in each table?  If you don't have a particular reason, then it would be better to remove as `ranking` can be easily calculated from the value of `count`.

**Comment by sehkone** [comment]
`ranking` was introduced in order to efficiently search data having `ranking` between a certain range.  But, for now, the search doesn't seem to be needed. It's Ok to remove it in the table.
